import nodemailer from "nodemailer";

export async function POST(request) {
  const { name, email, phone, subject, message } = await request.json();

  // Create transporter
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_PASSWORD,
    },
  });

  // Email to Ocean Lifespaces (admin)
  const adminMailOptions = {
    from: `Ocean Lifespaces Contact Form <${process.env.GMAIL_USER}>`,
    to: "salesinfra@olipl.com", // Your admin email
    subject: `New Contact Form Submission: ${subject}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">New Contact Request</h1>
        
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Phone:</strong> ${phone}</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <p><strong>Message:</strong></p>
          <p>${message.replace(/\n/g, "<br>")}</p>
        </div>
        
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>This email was automatically generated by the Ocean Lifespaces contact form.</p>
        </div>
      </div>
    `,
  };

  // Email to user (confirmation)
  const userMailOptions = {
    from: `Ocean Lifespaces <${process.env.GMAIL_USER}>`,
    to: email,
    subject: "Thank You for Contacting Ocean Lifespaces",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">Thank You for Contacting Us!</h1>
        
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p>We've received your message and will get back to you soon.</p>
          <p>Here's what you submitted:</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <p><strong>Message:</strong></p>
          <p>${message.replace(/\n/g, "<br>")}</p>
        </div>
        
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>If you need immediate assistance, please call us at [Your Phone Number]</p>
          <p>© ${new Date().getFullYear()} Ocean Lifespaces. All rights reserved.</p>
        </div>
      </div>
    `,
  };

  try {
    // Send both emails
    await transporter.sendMail(adminMailOptions);
    await transporter.sendMail(userMailOptions);

    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error sending email:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
