import nodemailer from "nodemailer";

export async function POST(request) {
  const { email } = await request.json();

  // Create Zoho Mail transporter (using same credentials as before)
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_PASSWORD,
    },
  });

  // Email content for subscriber
  const subscriberMailOptions = {
    from: `Ocean Lifespaces Newsletter <${process.env.ZOHO_MAIL_USER}>`,
    to: email,
    subject: "Thank You for Subscribing to Ocean Lifespaces Newsletter",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">Thank You for Subscribing!</h1>
        
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p>You've successfully subscribed to the Ocean Lifespaces newsletter. We'll keep you updated with our latest news, events, and updates.</p>
          <p>Your email: <strong>${email}</strong> has been added to our mailing list.</p>
        </div>
        
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>If this was a mistake or you wish to unsubscribe, please contact us at <a href="mailto:support@Ocean Lifespaces.org" style="color: #3182ce;">support@Ocean Lifespaces.org</a></p>
          <p>© ${new Date().getFullYear()} Ocean Lifespaces. All rights reserved.</p>
        </div>
      </div>
    `,
  };

  // Email content for president
  const presidentMailOptions = {
    from: `Ocean Lifespaces Newsletter <${process.env.ZOHO_MAIL_USER}>`,
    to: "reports@olipl.com",
    subject: `New Newsletter Subscriber: ${email}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">New Newsletter Subscription</h1>
        
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p>A new subscriber has joined the Ocean Lifespaces newsletter mailing list:</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Subscription Date:</strong> ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>This email was automatically generated by the Ocean Lifespaces newsletter system.</p>
        </div>
      </div>
    `,
  };

  try {
    // Send both emails
    await transporter.sendMail(subscriberMailOptions);
    await transporter.sendMail(presidentMailOptions);

    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error sending email via Zoho:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
        stack: process.env.NODE_ENV === "development" ? error.stack : undefined,
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
